### ISSUE TITLE
Getting an error when registering the route using the zoomWebhooks method

### ISSUE THREAD

**Issue by jakeones1** [binary-cats/laravel-zoom-webhooks#4]
I followed all the instructions when installing the package and still getting this error:

![Screenshot from 2021-10-02 22-10-40](https://user-images.githubusercontent.com/22153951/135730204-78917def-55f1-43d2-9a4d-b6e20d63aa1b.png)

What should I do in the routes/web.php file to get rid of this error? I'm using Laravel 7 for my project.

The route looks like this:
![Screenshot from 2021-10-02 22-59-07](https://user-images.githubusercontent.com/22153951/135730306-ea138ccb-e94e-4f7f-a950-dc2d82f537c0.png)

**Comment by cyrillkalita** [comment]
@jakeones1 

steps to replicate:
```bash
gh repo clone laravel/laravel && cd laravel && echo "Route::zoomWebhooks('webhooks/zoom');" >> routes/web.php
```

Your issue comes from `app\Providers\RouteServiceProvider` 

```php
    /**
     * This namespace is applied to your controller routes.
     *
     * In addition, it is set as the URL generator's root namespace.
     *
     * @var string
     */
    protected $namespace = 'App\Http\Controllers';
```
[Laravel 8 moved on to not force it onto users](https://laravel.com/docs/8.x/releases#routing-namespace-updates)

> In previous releases of Laravel, the RouteServiceProvider contained a $namespace property. This property's value would automatically be prefixed onto controller route definitions and calls to the action helper / URL::action method. In Laravel 8.x, this property is null by default. This means that no automatic namespace prefixing will be done by Laravel

To solve this particular issue on your end.
See what the macro does:
```php
        Route::macro('zoomWebhooks', function ($url) {
            return Route::post($url, ZoomWebhooksController::class);
        });
```
Thus you are free to declare the route yourself (in `web.php`):

```php
Route::post('webhooks/zoom', '\BinaryCats\ZoomWebhooks\ZoomWebhooksController');
```
